
name: CI


on:
  push:
    branches:
      - 'feature/*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
